language: python
python:
  - "2.7"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-scipy python-nose
    - sudo apt-get install python-pip
install:
    - python setup.py install
# command to run tests, e.g. python setup.py test
script:  nosetests .
